spring.application.name=InnowiseUserService
sping.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/main-changelog.xml
spring.datasource.url=jdbc:postgresql://localhost:5432/innowise_user_service
spring.datasource.username=postgres
spring.datasource.password=postgresql